// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { Stone, StoneData, StoneTableId } from "./tables/Stone.sol";
import { StonePos, StonePosData, StonePosTableId } from "./tables/StonePos.sol";
import { StoneToken, StoneTokenTableId } from "./tables/StoneToken.sol";
import { StoneUser, StoneUserTableId } from "./tables/StoneUser.sol";
import { UserToken, UserTokenData, UserTokenTableId } from "./tables/UserToken.sol";
import { UserName, UserNameTableId } from "./tables/UserName.sol";
import { Token, TokenData, TokenTableId } from "./tables/Token.sol";
import { TokenCount, TokenCountData, TokenCountTableId } from "./tables/TokenCount.sol";
