// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IStoneSystem {
  function spawnStone(int32 x, int32 y, address token, string memory color) external;
}
